name: Build and test all

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    - uses: bazel-contrib/setup-bazel@0.14.0
      with:
        bazelisk-cache: true
    - name: Build and test all modules
      env:
        HERMETIC_PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        bazel build //...
        bazel test //...
