name: Build and test all

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
        include:
          - os: macos-latest
            bazel-target: darwin
          - os: ubuntu-latest
            bazel-target: linux

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} for Linux
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: bazel-contrib/setup-bazel@0.14.0
      with:
        bazelisk-cache: true
    - name: Build and test all modules
      run: |
        bazel build //... --loading_phase_threads 2
        bazel test //...
