name: Publish to PyPI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-22.04]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    - uses: bazel-contrib/setup-bazel@0.14.0
      with:
        bazelisk-cache: true

    - name: View glibc version
      if: matrix.os == 'ubuntu-22.04'
      run: |
        ldd --version

    - name: Build
      env:
        HERMETIC_PYTHON_VERSION: ${{ matrix.python-version }}
      run: bazel build //:tensorflow_s3_wheel

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        pip install --upgrade pip
        pip install twine

        twine upload \
          --repository-url https://upload.pypi.org/legacy/ \
          bazel-bin/tensorflow_s3-*.whl
